language: bash
env:
  global:
    - DEPLOY_HOST=rpm.palette-software.com
    - DEPLOY_PATH=/var/palette-rpm-repo
    - DEPLOY_USER=palette-rpm
    # DEPLOY_PASS
    - secure: "MhN1zJozRsTGg2K0mdxcw2G3IE0cRiorfPfg8EkBI3ihrIygXmcJMh1XbJyvU00E703i7lJvUSOhQlfliZZN4dI6xxygoHZNvDezX/H8ezLqaeEsLuNNbbHjJn2/GwssLm/kRc4uD2bPJh+KfwNFWcdv3daivRc8kiS56ucjOdQV1WB2pa46L6VA+m2gYWn68CBDjS1lKRhkoVjbfOSs2pla5iMvjLcXoPYQ+lEs40fLFXeqsZdQE9qAyNa+C1B+KlRaYC07+eaEnmPjwRHwp/EG0DX1OL6ycCtB0DSxJVjzMKkKNU/TZV7bqpNONP0vGSX732U3wHgOsnFLPtW+OX95d10EqOICWfYxhFnO4DAhWRMbRVDQRWZKsGGKMzv82DtkGIyqIw3Rvu1Emg2zql/UscY+CM232p4ULZqgA35cUzexE03dXqYz1ZfQ2TCIyJusCEAEQuCGu+SpZqUnwuRpYXyl8rlNQov43/OO5/J4PL6aR0y1L5Uk+yqT3Fn3SmaSD91uTZC8PcavAmGw/4i5KacnEdOK1O0PKqqnCFQ9FBxzY97c3Vy6+rRlgHmAzFAYXYdGCR8NMC4OvwtVyNJRvICkzuPwbXkb0DDOWE4GM3yItWsjgMN/p7CqGYgvPT9Nb1Qu2GAsIReW/RX/RvcLHZmweiOudzMGM+jmv9k="
    # GITHUB_TOKEN
    - secure: SWr49SmcfrCIP/ugW3U6rlyhZEI8GTlyuSr/3CUl5L/jXUKC1xOK9WNdGyErJatHZaWkxG7fW6pcNtU6Aokgg/lIsTtI60UKiV7rhGJb9jqIiwhteVW03QSQpl29/0VM3eySGJ8mvxlqxFmyBg5w0QR6BJiEDF/3Kb2vhheOtCXjqOGV1+mLdkqztDEW0kOfxf2s49xz5P1sZaY3eVWZIexZ8QemRSIpsiOS+plXVbZP8gilB7iB8+brlaA5F0YNAARdoyI2CUMgAKJAy4xIyx7tPmMZe5nlZba/+pTjBCbFaGgSaurY+n0lqmMhu6XVV1CRZogb1BbxcMTYUswWao6qJDFaa6qpdgeveZOVMxE9YMBKn623TAoVFWCt11ZU0ty8eZKBLNATUZW2sw6G0YBVI/e5FpgBx2NdS31in+XhnG+oUQSjCfBdgP7SubbyuSu60H1AWx2UwMdeGF/TN81lqi/QgQ47yG7TW56Uuao/x5dHkAmXZy2IrMvCuUEW0r0bX9YxX0QBUbUKCIQ6DRmoDFRgQXcmdb2sIAwKubhOisE1ZATMTMNUmJ0fu/vN5wJ2fdjMv7lkA2ThvJf78/Ga0VFoDmrFlTanBY5OWpQm2V+A+YMIdZ4dDQm5E7GgPvY/LXgoYD2cQ88ozvY9KucmHVwjuzWpsUoVhMESGHI=
branches:
  only:
    - MANUAL_TRIGGER
addons:
  apt:
    packages:
      - rpm
      - sshpass
install: true
script:
  - rpmbuild -bb --buildroot $(pwd) -D "version ${PALETTE_AGENT_VERSION}" -D "github_token ${GITHUB_TOKEN}" -D "buildrelease 1" -D "_rpmdir rpm-build/_build" insight-agent.spec
deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    branch: master

notifications:
  email:
    on_success: never
    on_failure: never
