language: bash
branches:
  only:
    - MANUAL_TRIGGER
addons:
  apt:
    packages:
      - rpm
install: true
script:
    - rpmbuild -bb --buildroot $(pwd) -D "version ${PALETTE_AGENT_VERSION}" -D "buildrelease 1" -D "_rpmdir $(pwd)/_build" insight-agent.spec
