version: 1.6.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - production
configuration: Release
platform: Any CPU
build_script:
- cmd: >-
    nuget.exe restore

    "C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe" "PalMon.sln" /verbosity:minimal /p:Configuration=Release /p:Platform="Mixed Platforms" /t:Clean /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    "C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe" "PalMon.sln" /verbosity:minimal /p:Configuration=Release /p:Platform="Mixed Platforms"  /t:Build /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    move PalMonServiceInstaller\bin\Release\PalMon.msi PalMonServiceInstaller\bin\Release\Palette-Black-Box-Recorder-v%APPVEYOR_BUILD_VERSION%-beta-installer.msi
test_script:
    - echo "Try a Palette Insight install and uninstall"
    - cd PalMonServiceInstaller\bin\Release\
    - set PALIN_MSI=Palette-Black-Box-Recorder-v%APPVEYOR_BUILD_VERSION%-beta-installer.msi
    - msiexec.exe /qn /i %PALIN_MSI%
    - echo "Installed Palette Insight successfully"
    - ps: (New-Object Net.WebClient).DownloadFile('https://github.com/palette-software/insight-tester/releases/download/v0.0/windows_amd64.zip', 'insight-tester.zip')
    - echo "Downloaded insight-tester"
    - msiexec.exe /qn /x %PALIN_MSI%
    - echo "Uninstalled Palette Insight successfully"

artifacts:
- path: PalMonServiceInstaller\bin\Release\*.msi
  name: Github
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)-beta
  release: Palette Black Box Recorder v$(appveyor_build_version)-beta
  auth_token:
    secure: Y8zvK91qR+RxmrmqdSPNYGAoLJFytPzX6cVSnHv4LY358RJfTrpzwiWuDumqYNps
  artifact: '*.msi'
  draft: true
  prerelease: true
  on:
    branch: production
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  auth_token:
    secure: YID5KzjUO9Nx2GlLOibJMA==
  channel: dev
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true

on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
