PollInterval: 30
ThreadInfoPollInterval: 15
LogPollInterval: 300
DBWriteInterval: 60
RepoTablesPollInterval: 3600
AllProcesses: true
ProcessedFilesTTL: 604800	# Default is a week
StorageLimit: 1024			# Default is 1 Gb. This value is given in megabytes.


Database: 
  Host: localhost
  Port: 5432
  Database: palette
  User: palette
  Password: password
  CommandTimeout: 600

# To use the webservice output, uncomment the following lines:
 
# Webservice:
#  Endpoint: http://localhost:9000

Logs: 
  - 
    Directory: 'c:\ProgramData\Tableau\Tableau Server\data\tabsvc\vizqlserver\Logs\'
    Filter: '*.txt'
  - 
    Directory: 'c:\ProgramData\Tableau\Tableau Server\data\tabsvc\logs\vizqlserver\'
    Filter: 'tabprotosrv*.txt'
TableauRepo: 
  Host: localhost
  Port: 8060
  Database: workgroup
  User: readonly
  Password: onlyread
