# Default values are commented out, so that they can be more easily updated with newer releases.
# Simply uncomment those ones where you need different values.

#UseCounterSamples: true
#UseLogPolling: true
UseRepoPolling: false
UseThreadInfo: false

IsPrimaryNode: true

# The following values are all given in seconds.
PollInterval: 10
#ThreadInfoPollInterval: 15
LogPollInterval: 15
#RepoTablesPollInterval: 3600		# This value effects only on primary nodes.
#StreamingTablesPollInterval: 600	# This value effects only on primary nodes.
#ProcessedFilesTTL: 0				# Default is not to keep processed files.

#StorageLimit: 10240				# Given in megabytes. Default is 10 GB.

# The maximum number of log lines that will be read and uploaded in a single batch
#LogLinesPerBatch: 10000

LicenseKey: c1d61023-249e-423c-bf2b-af9388f47d48    # This is just an example GUID, this is not a valid license

Webservice:
 Endpoint: http://localhost:9000

Logs:
  -
    Directory: 'c:\Users\Peter\Munka\nflx-out-of-memory\vizqlserver\Logs\'
    Filter: '*.txt'
  -
    Directory: 'c:\Users\Peter\Munka\nflx-out-of-memory\vizqlserver\'
    Filter: 'tabprotosrv*.txt'
  - 
    Directory: 'c:\Users\Peter\Munka\nflx-out-of-memory\vizqlserver\'
    Filter: 'tdeserver*.txt'
    Format: 'plain'
  -
    Directory: 'c:\Users\Peter\Munka\nflx-out-of-memory\dataengine\'
    Filter: 'tdeserver*.log'
    Format: 'plain'

TableauRepo: 
  Host: 192.168.221.30
  Port: 8060
  Database: workgroup
  User: readonly
  Password: onlyr3ad
