UseCounterSamples: true
UseLogPolling: true
UseRepoPolling: true
UseThreadInfo: true

PollInterval: 30
ThreadInfoPollInterval: 15
LogPollInterval: 300
DBWriteInterval: 60
RepoTablesPollInterval: 60
AllProcesses: true
ProcessedFilesTTL: 3600        # Given in seconds. Default is not to keep processed files.
StorageLimit: 16          # Given in megabytes. Default is 1 Gb.


Database: 
  Host: localhost
  Port: 5432
  Database: palette
  User: palette
  Password: password
  CommandTimeout: 600

# To use the webservice output, uncomment the following lines:
 
Webservice:
  Endpoint: http://localhost:9000

TableauRepo: 
  Host: 88.151.101.150
  Port: 8060
  Database: workgroup
  User: readonly
  Password: onlyr3ad

