# Default values are commented out, so that they can be more easily updated with newer releases.
# Simply uncomment those ones where you need different values.

#UseCounterSamples: true
#UseLogPolling: true
#UseRepoPolling: true
#UseThreadInfo: true

# The following values are all given in seconds.
#PollInterval: 30
#ThreadInfoPollInterval: 15
#LogPollInterval: 300
RepoTablesPollInterval: 3600	# This value must be set to 0 for worker nodes.
#ProcessedFilesTTL: 0			# Default is not to keep processed files.

#StorageLimit: 1024				# Given in megabytes. Default is 10 GB.

# The maximum number of log lines that will be read and uploaded in a single batch
#LogLinesPerBatch: 10000

Webservice:
 Endpoint: http://localhost:9000

Logs:
  -
    Directory: 'c:\ProgramData\Tableau\Tableau Server\data\tabsvc\vizqlserver\Logs\'
    Filter: '*.txt'
  -
    Directory: 'c:\ProgramData\Tableau\Tableau Server\data\tabsvc\logs\vizqlserver\'
    Filter: 'tabprotosrv*.txt'
TableauRepo: 
  Host: localhost
  Port: 8060
  Database: workgroup
  User: readonly
  Password: onlyread
