# Default values are commented out, so that they can be more easily updated with newer releases.
# Simply uncomment those ones where you need different values.

UseCounterSamples: false
#UseLogPolling: true
#UseRepoPolling: true
#UseThreadInfo: true

# The following values are all given in seconds.
#PollInterval: 30
#ThreadInfoPollInterval: 15
#LogPollInterval: 300
#RepoTablesPollInterval: 3600		# This value has effect only on Tableau repository nodes.
#StreamingTablesPollInterval: 300	# This value has effect only on Tableau repository nodes.
#PreferPassiveRepository: true      # By default poll Tableau's passive repository if it exists
#ProcessedFilesTTL: 0				# Default is not to keep processed files.

#StorageLimit: 10240				# Given in megabytes. Default is 10 GB.

# The maximum number of log lines that will be read and uploaded in a single batch
#LogLinesPerBatch: 10000

InsightAuthToken: 34e6a6cc-a5ab-4c36-8129-15fc0d61069f    # This is just an example GUID, this is not a valid license

Webservice:
 Endpoint: http://localhost:9000
 # UseProxy: false
 # ProxyAddress: http://proxy-example  # This is not the default value, just an example
 # ProxyUsername: tom
 # ProxyPassword: jerry

# Log folders and Tableau settings are detected automatically since version 2.0.16
# Logs:
#   -
#     Directory: 'c:\ProgramData\Tableau\Tableau Server\data\tabsvc\vizqlserver\Logs\'
#     Filter: '*.txt'
#   -
#     Directory: 'c:\ProgramData\Tableau\Tableau Server\data\tabsvc\logs\vizqlserver\'
#     Filter: 'tabprotosrv*.txt'
#   -
#     Directory: 'c:\ProgramData\Tableau\Tableau Server\data\tabsvc\logs\vizqlserver\'
#     Filter: 'tdeserver*.txt'
#     Format: 'plain'
#   -
#     Directory: 'c:\ProgramData\Tableau\Tableau Server\data\tabsvc\logs\dataengine\'
#     Filter: 'tdeserver*.log'
#     Format: 'plain'

# TableauRepo:
#   Host: localhost
#   Port: 8060
#   Database: workgroup
#   User: readonly
#   Password: onlyread
