- Directory: 'tabsvc\vizqlserver\Logs'
  Filter: '*.txt'
  Format: 'json'
- Directory: 'tabsvc\logs\vizqlserver'
  Filter: 'tabprotosrv*.txt'
  Format: 'json'
- Directory: 'tabsvc\logs\vizqlserver'
  Filter: 'tdeserver*.txt'
  Format: 'plain'
