- Directory: 'tabsvc\vizqlserver\Logs'
  Filter: 'vizqlserver*.txt'
  ProcessName: 'vizqlserver'
- Directory: 'tabsvc\vizqlserver\Logs'
  Filter: 'dataserver*.txt'
  ProcessName: 'dataserver'
- Directory: 'tabsvc\logs\hyper'
  Filter: 'hyper*.log'
  ProcessName: 'hyper'
- Directory: 'tabsvc\vizqlserver\Logs'
  Filter: 'backgrounder*.txt'
  ProcessName: 'backgrounder'