- 
    Name: sites
- 
    Name: projects
- 
    Name: users
- 
    Name: workbooks
-
    Name: historical_event_types
    Full: false
    Field: type_id
-
    Name: historical_events
    Full: false
    Field: id
-
    Name: hist_capabilities
    Full: false
    Field: id
-
    Name: hist_comments
    Full: false
    Field: id
-
    Name: hist_configs
    Full: false
    Field: id
-
    Name: hist_data_connections
    Full: false
    Field: id
-
    Name: hist_datasources
    Full: false
    Field: id
-
    Name: hist_groups
    Full: false
    Field: id
-
    Name: hist_licensing_roles
    Full: false
    Field: id
-
    Name: hist_projects
    Full: false
    Field: id
-
    Name: hist_schedules
    Full: false
    Field: id
-
    Name: hist_sites
    Full: false
    Field: id
-
    Name: hist_tags   
    Full: false
    Field: id
-
    Name: hist_tasks
    Full: false
    Field: id
-
    Name: hist_users
    Full: false
    Field: id
-
    Name: hist_views
    Full: false
    Field: id
-
    Name: hist_workbooks
    Full: false
    Field: id
- 
    Name: views
- 
    Name: system_users
- 
    Name: core_licenses
- 
    Name: data_connections
- 
    Name: datasources
- 
    Name: monitoring_postgresql
- 
    Name: monitoring_dataengine
- 
    Name: extracts
- 
    Name: groups
- 
    Name: group_users
- 
    Name: tasks
- 
    Name: schedules
-
    Name: http_requests
    Full: false
    Field: id
-
    Name: background_jobs
    Full: false
    Field: updated_at
    Filter: 'progress = 100'
-
    Name: async_jobs
    Full: false
    Field: updated_at
    Filter: 'progress = 100'