- 
    Name: sites
- 
    Name: projects
- 
    Name: users
- 
    Name: workbooks
-
    Name: views
-
    Name: system_users
-
    Name: data_connections
-
    Name: datasources
-
    Name: http_requests
    Full: false
    Field: id 
-
    Name: background_jobs
    Full: false
    Field: updated_at
    Filter: 'progress = 100'