- 
    Name: sites
- 
    Name: projects
- 
    Name: users
- 
    Name: workbooks
-
    Name: historical_events
-
    Name: hist_capabilities
-
    Name: hist_comments
-
    Name: hist_configs
-
    Name: hist_data_connections
-
    Name: hist_datasources
-
    Name: hist_groups
-
    Name: hist_licensing_roles
-
    Name: hist_projects
-
    Name: hist_schedules
-
    Name: hist_sites
-
    Name: hist_tags   
-
    Name: hist_tasks
-
    Name: hist_users
-
    Name: hist_views
-
    Name: hist_workbooks
- 
    Name: views
- 
    Name: system_users
- 
    Name: core_licenses
- 
    Name: data_connections
- 
    Name: datasources
- 
    Name: monitoring_postgresql
- 
    Name: monitoring_dataengine
- 
    Name: extracts
- 
    Name: groups
- 
    Name: group_users
- 
    Name: tasks
- 
    Name: schedules
-
    Name: http_requests
    Full: false
    Field: id
-
    Name: background_jobs
    Full: false
    Field: updated_at
    Filter: 'progress = 100'
-
    Name: async_jobs
    Full: false
    Field: updated_at
    Filter: 'progress = 100'